Syllia/apps/accounts/urls.py
from django.conf.urls import patterns, url

from Syllia.apps.accounts import views

urlpatterns = patterns('',
   url(r'^register/$', views.RegisterView.as_view(), name='register'),
   url(r'^update_profile/$', views.update_profile, name='update_profile'),
   url(r'^change_password/$', views.change_password, name='change_password'),
)

Syllia/apps/syllabus/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from Syllia.apps.syllabus import views, pdf

urlpatterns = patterns('',
    # url(r'^$', login_required(DashboardView.as_view()), name='index'),
    url(r'^syllabus/new/$', login_required(views.SyllabusView.as_view()), name='syllabus'),
    url(r'^syllabus/(\d+)/$', login_required(views.SyllabusView.as_view()), name='syllabus'),
    url(r'^syllabus/delete/$', views.delete_syllabus, name='delete_syllabus'),
    url(r'^rubric/new/$', login_required(views.RubricView.as_view()), name='rubric'),
    url(r'^rubric/(\d+)/$', login_required(views.RubricView.as_view()), name='rubric'),
    url(r'^rubric/delete/$', views.delete_rubric, name='delete_rubric'),
    url(r'^pdf/$', pdf.return_a_pdf, name='pdf'),
    url(r'^pdf/mult/$', pdf.return_a_zip),
    url(r'^feedback/$', login_required(views.FeedbackView.as_view()), name='feedback'),
)

Syllia/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView

from Syllia.apps.syllabus.views import DashboardView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
   # url(r'^accounts/', include('accounts.urls', namespace="accounts")),
   # url(r'^$', TemplateView.as_view(template_name='home/index.html'), name='index'),

   # Syllabus App
   url(r'^$', DashboardView.as_view(), name='index'),
   url(r'^', include('Syllia.apps.syllabus.urls', namespace='syllabus')),

   # Static pages
   url(r'^about/$', TemplateView.as_view(template_name='home/about.html'), name='about'),
   url(r'^contact/$', TemplateView.as_view(template_name='home/contact.html'), name='contact'),
   # url(r'^rubric/$', TemplateView.as_view(template_name='home/rubric.html'), name='rubric'),
   # url(r'^dashboard/$', TemplateView.as_view(template_name='home/dashboard.html'), name='dashboard'),

   # Accounts and authentication
   url(r'^accounts/', include('authtools.urls', namespace='authtools')),
   url(r'^accounts/', include('Syllia.apps.accounts.urls', namespace='accounts')),

   # Admin
   url(r'^admin/', include(admin.site.urls)),
)

syllabus/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from syllabus.views import SyllabusView, DashboardView, RubricView

urlpatterns = patterns('',
    # url(r'^$', login_required(DashboardView.as_view()), name='index'),
    url(r'^syllabus/new/$', login_required(SyllabusView.as_view()), name='syllabus'),
    url(r'^syllabus/(\d+)/$', login_required(SyllabusView.as_view()), name='syllabus'),
    url(r'^rubric/new/$', login_required(RubricView.as_view()), name='rubric'),
    url(r'^rubric/(\d+)/$', login_required(RubricView.as_view()), name='rubric'),
    # url(r'^profile/$', ProfileView.as_view(), name='profile'),
    # url(r'^register/$', RegisterView.as_view(), name='register'),
)

Syllia/apps/syllabus/models.py
from jsonfield import JSONField

from django.db import models
from django.contrib.auth import get_user_model
from django.contrib import admin
# Create your models here.


class Rubric(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(get_user_model())
    rubric_name = models.CharField(max_length=50)
    json_data = JSONField(default={"pk": 0})
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.id == None:
            super(Rubric, self).save(*args, **kwargs)
            self.json_data['pk'] = self.id

        super(Rubric, self).save(*args, **kwargs)

    def json(self):
        return {"pk": self.id, "rubricName": self.rubric_name}

    def __unicode__(self):
        return self.rubric_name


class College(models.Model):
    id = models.AutoField(primary_key=True)
    college_name = models.CharField(max_length=50)

    def json(self):
        return {"pk": self.id, "collegeName": self.college_name}

    def __unicode__(self):
        return self.college_name


class Department(models.Model):
    id = models.AutoField(primary_key=True)
    department_name = models.CharField(max_length=50)
    college = models.ForeignKey('syllabus.College')

    def json(self):
        return {"pk": self.id, "departmentName": self.department_name, "college": self.college.id}

    def __unicode__(self):
        return self.department_name


class Syllabus(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(get_user_model())
    syllabus_name = models.CharField(max_length=50)
    department = models.ForeignKey('syllabus.Department')
    course_code = models.CharField(max_length=7)
    rubric = models.ForeignKey(
        'syllabus.Rubric', blank=True, null=True, on_delete=models.SET_NULL)
    json_data = JSONField(default={"pk": 0})
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.id == None:
            super(Syllabus, self).save(*args, **kwargs)
            self.json_data['pk'] = self.id

        super(Syllabus, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.course_code


class Feedback(models.Model):
    id = models.AutoField(primary_key=True)
    fullname = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    feedback = models.TextField()

Syllia/apps/accounts/forms.py
from django import forms
from Syllia.apps.syllabus.models import Department, College


class ProfileForm(forms.Form):
    name = forms.CharField()
    college = forms.ModelChoiceField(queryset=College.objects.all())
    department = forms.ModelChoiceField(queryset=Department.objects.all())


class RegisterForm(ProfileForm):
    email = forms.EmailField(label='Email Address')
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean_confirm_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']

        if password != confirm_password:
            raise forms.ValidationError("The passwords do not match.")

        return password

    def clean_email(self):
        email = self.cleaned_data['email']

        if not "@dlsu.edu.ph" in email and not "@delasalle.ph" in email:
            raise forms.ValidationError(
                "You need to use a valid @dlsu.edu.ph or @delasalle.ph email address to sign up for this service.")

        return email

Syllia/apps/syllabus/forms.py
from django.forms import ModelForm
from Syllia.apps.syllabus.models import Feedback


class FeedbackForm(ModelForm):

    class Meta:
        model = Feedback

Syllia/apps/syllabus/views.py
# Create your views here.

from datetime import datetime, timedelta

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.views.generic.base import View
from django.http import Http404, HttpResponse, HttpResponseServerError
from django.shortcuts import render, redirect
from django.utils import simplejson, timezone
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required

from Syllia.apps.syllabus.models import Rubric, College, Department, Syllabus
from Syllia.apps.accounts.forms import ProfileForm
from Syllia.apps.syllabus.forms import FeedbackForm


# import logging

# Log everything, and send it to stderr.
# logging.basicConfig(level=logging.DEBUG)

class DashboardView(View):
    template_name = 'syllabus/dashboard.html'

    def get(self, request, *args, **kwargs):
        # If not authenticated, show home page
        if not request.user.is_authenticated():
            return render(request, 'home/index.html', {'home_page': True})

        # Else. Dashboard
        current_user = get_user_model().objects.get(
            email=request.user.email)

        # TODO: Make more DRY
        syllabus_set = current_user.syllabus_set.all()
        syllabusList = []

        for syllabus in syllabus_set:
            syllabusList.append({
                "pk": syllabus.id,
                "url": 'syllabus',
                "itemName": syllabus.syllabus_name,
                "lastModified": format_last_modified_time(syllabus.last_modified)
            })

        rubric_set = current_user.rubric_set.all()
        rubricList = []

        for rubric in rubric_set:
            rubricList.append({
                "pk": rubric.id,
                "url": 'rubric',
                "itemName": rubric.rubric_name,
                "lastModified": format_last_modified_time(rubric.last_modified)
            })

        profileData = {
            "college": current_user.faculty.department.college.id,
            "department": current_user.faculty.department.id
        }

        jsonData = {
            "syllabusList": syllabusList,
            "rubricList": rubricList,
            "collegeList": get_college_list(),
            "departmentList": get_department_list(),
            "profileData": profileData
        }

        context = {
            'jsonData': simplejson.dumps(jsonData)
        }

        # Load profile form
        if request.session.get('profile_form'):
            context['profile_form'] = request.session['profile_form']
            del request.session['profile_form']
        else:
            context['profile_form'] = ProfileForm(initial={
                'name': current_user.get_full_name()
            })

        # Load change password form
        if request.session.get('change_password_form'):
            context['change_password_form'] = request.session[
                'change_password_form']
            del request.session['change_password_form']
        else:
            context['change_password_form'] = PasswordChangeForm(current_user)

        return render(request, self.template_name, context)


class SyllabusView(View):
    template_name = 'syllabus/syllabus.html'

    def get(self, request, *args, **kwargs):
        current_user = get_user_model().objects.get(
            email=request.user.email)

        # Create dictionary
        jsonData = {}

        # If edit mode, load syllabus data
        if(len(args)):
            try:
                syllabus = current_user.syllabus_set.get(pk=args[0])
                jsonData['syllabusData'] = syllabus.json_data

                # Load modified time data
                jsonData['timeSinceModified'] = get_time_since_modified(
                    syllabus.last_modified)

            except Exception:
                raise Http404

        rubricList = []
        rubrics = current_user.rubric_set.all()

        for rubric in rubrics:
            rubricList.append(rubric.json())

        jsonData['rubricList'] = rubricList

        jsonData['collegeList'] = get_college_list()
        jsonData['departmentList'] = get_department_list()

        # If reached here, no arguments. Return empty form
        return render(request, self.template_name, {"jsonData": simplejson.dumps(jsonData)})

    def post(self, request, *args, **kwargs):
        # Deserialize to dictionary
        json_data = simplejson.loads(request.POST['syllabus_json'])

        current_user = get_user_model().objects.get(email=request.user.email)

        # Load or create new syllabus
        try:
            syllabus = current_user.syllabus_set.get(pk=int(json_data['pk']))
        except Exception:
            syllabus = Syllabus()

        try:
            # Initialize
            syllabus.user = current_user
            syllabus.syllabus_name = json_data['syllabusName']
            syllabus.course_code = json_data['courseCode']
            syllabus.json_data = json_data

            # Load foreign keys
            # These will throw an exception if invalid
            syllabus.department = Department.objects.get(
                pk=json_data['department'])
            if('rubric' in json_data):
                syllabus.rubric = current_user.rubric_set.get(
                    pk=json_data['rubric'])

            syllabus.save()

            response_data = {
                'viewModel': syllabus.json_data,
                'timeSinceModified': get_time_since_modified(syllabus.last_modified)
            }

            if request.POST['redirect'] == "true":
                messages.success(request, 'Saved syllabus')
                response_data['redirectTo'] = reverse('index')

            return HttpResponse(simplejson.dumps(response_data), content_type="application/json")
        except Exception:
            return HttpResponseServerError(simplejson.dumps({'message': 'You must at least have basic information before saving.'}), content_type="application/json")


@csrf_protect
@login_required
def delete_syllabus(request):
    if request.method == "POST":
        item_ids = request.POST.getlist('ids_json[]')

        response_data = {}
        current_user = get_user_model().objects.get(
            email=request.user.email)

        try:
            current_user.syllabus_set.filter(id__in=item_ids).delete()
            response_data['success'] = True
            return HttpResponse(simplejson.dumps(response_data), content_type="application/json")
        except Exception:
            return HttpResponseServerError(simplejson.dumps({'message': 'Something went wrong.'}), content_type="application/json")


class RubricView(View):
    template_name = 'syllabus/rubric.html'

    def get(self, request, *args, **kwargs):
        if(len(args)):
            current_user = get_user_model().objects.get(
                email=request.user.email)

            try:
                rubric = current_user.rubric_set.get(pk=args[0])

                jsonData = {
                    'rubricData': rubric.json_data,
                    'timeSinceModified': get_time_since_modified(rubric.last_modified)
                }

                context = {'jsonData': simplejson.dumps(jsonData)}
                return render(request, self.template_name, context)
            except Exception:
                raise Http404

        # If reached here, no arguments. Return empty form
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        # Deserialize
        json_data = simplejson.loads(request.POST['rubric_json'])

        current_user = get_user_model().objects.get(email=request.user.email)

        rubric = None
        try:
            rubric = current_user.rubric_set.get(pk=int(json_data['pk']))
        except Exception:
            rubric = Rubric()

        try:
            rubric.user = current_user
            rubric.rubric_name = json_data['rubricName']
            rubric.json_data = json_data

            rubric.save()

            messages.success(request, 'Saved rubric')
            return redirect('index')
        except Exception:
            jsonData = {
                'rubricData': json_data
            }

            context = {'jsonData': simplejson.dumps(jsonData)}
            messages.error(request, 'Please check your forms')
            return render(request, self.template_name, context)


@csrf_protect
@login_required
def delete_rubric(request):
    if request.method == "POST":
        item_ids = request.POST.getlist('ids_json[]')

        response_data = {}
        current_user = get_user_model().objects.get(
            email=request.user.email)

        try:
            current_user.rubric_set.filter(id__in=item_ids).delete()
            response_data['success'] = True
            return HttpResponse(simplejson.dumps(response_data), content_type="application/json")
        except Exception:
            return HttpResponseServerError(simplejson.dumps({'message': 'Something went wrong.'}), content_type="application/json")


class FeedbackView(View):
    template_name = 'home/feedback.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        form = FeedbackForm(request.POST)

        if form.is_valid():
            form.save()
            return render(request, 'home/feedback_thanks.html')

        return render(request, 'home/feedback.html', {'form': form})


# static methods
def format_last_modified_time(last_modified):
    if timezone.localtime(last_modified).date() == timezone.localtime(datetime.utcnow().replace(tzinfo=timezone.utc)).date():
        last_modified_string = timezone.localtime(
            last_modified).strftime('%I:%M %p')
    else:
        last_modified_string = timezone.localtime(
            last_modified).strftime('%b %d')

Syllia/apps/syllabus/templates/syllabus/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock title %}

{% block content %}


<div class="row content-header">
    <div class="large-12 column">
        <h3>Account Dashboard</h3>
        <!--<span>Modified x minutes ago</span>-->
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

<div class="row top-spacing">
    <div class="section-container vertical-tabs" data-section="vertical-tabs" data-options="deep_linking: true">
        <section class="active">
            <p class="title" data-section-title>
                <a href="#syllabus">Syllabus</a>
            </p>
            <div class="content" data-slug="syllabus" data-section-content>
                <!-- Content -->
                <div class="row">
                    <div class="large-12 columns">

                        <a id="multiSelector" href="#" class="dashboard-grey dropdown">
                            <i class="icon-check" style="display:none;"></i>
                            <i class="icon-check-minus" style="display:none;"></i>
                            <i class="icon-check-empty"></i>
                        </a>

                        <a href="{% url "syllabus:syllabus" %}" class="dashboard-green"><i class="icon-plus"></i>&nbsp;New Syllabus</a>

                        <a id="btnDownload" href="#" class="dashboard-green" style="display: none;"><i class="icon-download-alt"></i>&nbsp;Download</a>
                        <a id="btnDownloadAll" href="#" class="dashboard-green" style="display: none;"><i class="icon-download-alt"></i>&nbsp;Download All</a>

                        <a id="btnDelete" href="#" class="dashboard-grey" style="display: none;"><i class="icon-trash"></i></a>
                        <a id="btnSure" href="#" class="dashboard-grey" style="display: none;">Are you sure?</a>
                        <a id="btnConfirm" href="#" class="dashboard-green" style="display: none;"><i class="icon-ok"></i></a>
                        <a id="btnCancel" href="#" class="dashboard-red" style="display: none;"><i class="icon-remove"></i></a>
                    </div>
                </div>


                <div class="row dashboard-table-content">
                    <div class="large-12 columns">
                        <ul data-bind="foreach: pagedList">
                            <li data-bind="click: select">
                                <!-- <i class="icon-check-empty"></i> -->
                                <input type="checkbox" data-bind="checked: isSelected">
                                <span class="itemName" data-bind="text: itemName"></span>
                                <span class="lastModified" data-bind="text: lastModified"></span>
                            </li>
                        </ul>
                        <div data-bind="visible: hasMoreThanOnePage">
                            <a class="dashboard-green" data-bind="click: previousPage">Previous</a>
                            <a class="dashboard-green" data-bind="click: nextPage">Next</a>
                        </div>
                    </div>
                </div>

                <!-- End of content -->
            </div>
            <form id="formDownload" action="{% url "syllabus:pdf" %}" style="display: none;" method="post">
                {% csrf_token %}
                <input id="inputDownload" name="pk" type="hidden">
            </form>
        </section>
        <section>
            <p class="title" data-section-title>
                <a href="#rubric">Rubric</a>
            </p>
            <div class="content" data-slug="rubric" data-section-content>
                <!-- Content -->
                <div class="row">
                    <div class="large-12 columns">

                        <a id="multiSelector" href="#" class="dashboard-grey dropdown">
                            <i class="icon-check" style="display:none;"></i>
                            <i class="icon-check-minus" style="display:none;"></i>
                            <i class="icon-check-empty"></i>
                        </a>

                        <a href="{% url "syllabus:rubric" %}" class="dashboard-green"><i class="icon-plus"></i>&nbsp;New Rubric</a>

                        <a id="btnDelete" href="#" class="dashboard-grey" style="display: none;"><i class="icon-trash"></i></a>
                        <a id="btnSure" href="#" class="dashboard-grey" style="display: none;">Are you sure?</a>
                        <a id="btnConfirm" href="#" class="dashboard-green" style="display: none;"><i class="icon-ok"></i></a>
                        <a id="btnCancel" href="#" class="dashboard-red" style="display: none;"><i class="icon-remove"></i></a>
                    </div>
                </div>


                <div class="row dashboard-table-content">
                    <div class="large-12 columns">
                        <ul data-bind="foreach: pagedList">
                            <li data-bind="click: select">
                                <!-- <i class="icon-check-empty"></i> -->
                                <input type="checkbox" data-bind="checked: isSelected">
                                <span class="itemName" data-bind="text: itemName"></span>
                                <span class="lastModified" data-bind="text: lastModified"></span>
                            </li>
                        </ul>
                        <div data-bind="visible: hasMoreThanOnePage">
                            <a class="dashboard-green" data-bind="click: previousPage">Previous</a>
                            <a class="dashboard-green" data-bind="click: nextPage">Next</a>
                        </div>
                    </div>
                </div>

                <!-- End of content -->
            </div>
        </section>
        <section>
            <p class="title" data-section-title>
                <a href="#user-profile">User Profile</a>
            </p>
            <div class="content" data-slug="user-profile" data-section-content>
                <h4>User Profile</h4>
                <form id="profileForm" action="{% url "accounts:update_profile" %}" method="post" class="custom">
                    {% csrf_token %}
                    <div class="row">
                        <div class="large-6 columns">
                            <label>Name</label>
                            {# <input id="id_name" name="name" type="text"/> #}
                            {{ profile_form.name }}
                            {{ profile_form.name.errors }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-6 columns">
                            <label>College</label>
                            <select id="collegeSelect" name="college" data-bind="options: collegeList,optionsText: 'collegeName',optionsValue: 'pk',value: college,optionsCaption: 'Choose one...'">
                            </select>
                            {# {{ profile_form.college }} #}
                            {{ profile_form.college.errors }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-6 columns">
                            <label>Department</label>
                            <select id="departmentSelect" name="department" data-bind="options: departmentList,optionsText: 'departmentName',
                            optionsValue: 'pk',value: department,optionsCaption: 'Choose one...'">
                            </select>
                            {# {{ profile_form.department }} #}
                            {{ profile_form.department.errors }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <a class="add-row" id="btnProfileSubmit" href="#"><i class="icon-edit"></i>&nbsp;Update Profile</a>
                        </div>
                    </div>
                </form>
            </div>
        </section>
        <section>
            <p class="title" data-section-title>
                <a href="#change-password">Change Password</a>
            </p>
            <div class="content" data-slug="change-password" data-section-content>
                <h4>Change Password</h4>
                <form id="change_password_form" action="{% url "accounts:change_password" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="large-6 columns">
                            <!-- <label>Old Password</label>
                            <input type="password"/> -->
                            {{ change_password_form.old_password.label }}
                            {{ change_password_form.old_password }}
                            {{ change_password_form.old_password.errors }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-6 columns">
                            <!-- <label>New Password</label>
                            <input type="password"/> -->
                            {{ change_password_form.new_password1.label }}
                            {{ change_password_form.new_password1 }}
                            {{ change_password_form.new_password1.errors }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-6 columns">
                            <!-- <label>Confirm Password</label>
                            <input type="password"/> -->
                            {{ change_password_form.new_password2.label }}
                            {{ change_password_form.new_password2 }}
                            {{ change_password_form.new_password2.errors }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="large-12 columns">
                            <a id="btnChangePasswordSubmit" class="add-row" href="#"><i class="icon-edit"></i>&nbsp;Change Password</a>
                        </div>
                    </div>
                </form>
            </div>
        </section>
    </div>
</div>

{% endblock content %}
{% block scripts %}

<!-- Server side json data -->
<script>
    var jsonData = $.parseJSON('{{ jsonData|escapejs }}');
</script>

{% load staticfiles %}
<script src="{% static "javascripts/vendor/knockout-2.3.0.js" %}"></script>
<script src="{% static "javascripts/profile.js" %}"></script>
<script src="{% static "javascripts/dashboard.js" %}"></script>
<script src="{% static "javascripts/ajax.js" %}"></script>
{% endblock scripts %}