Syllia/apps/accounts/urls.py
from django.conf.urls import patterns, url

from Syllia.apps.accounts import views

urlpatterns = patterns('',
   url(r'^register/$', views.RegisterView.as_view(), name='register'),
   url(r'^update_profile/$', views.update_profile, name='update_profile'),
   url(r'^change_password/$', views.change_password, name='change_password'),
)

Syllia/apps/syllabus/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from Syllia.apps.syllabus import views, pdf

urlpatterns = patterns('',
    # url(r'^$', login_required(DashboardView.as_view()), name='index'),
    url(r'^syllabus/new/$', login_required(views.SyllabusView.as_view()), name='syllabus'),
    url(r'^syllabus/(\d+)/$', login_required(views.SyllabusView.as_view()), name='syllabus'),
    url(r'^syllabus/delete/$', views.delete_syllabus, name='delete_syllabus'),
    url(r'^rubric/new/$', login_required(views.RubricView.as_view()), name='rubric'),
    url(r'^rubric/(\d+)/$', login_required(views.RubricView.as_view()), name='rubric'),
    url(r'^rubric/delete/$', views.delete_rubric, name='delete_rubric'),
    url(r'^pdf/$', pdf.return_a_pdf, name='pdf'),
    url(r'^pdf/mult/$', pdf.return_a_zip),
    url(r'^feedback/$', login_required(views.FeedbackView.as_view()), name='feedback'),
)

Syllia/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView

from Syllia.apps.syllabus.views import DashboardView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
   # url(r'^accounts/', include('accounts.urls', namespace="accounts")),
   # url(r'^$', TemplateView.as_view(template_name='home/index.html'), name='index'),

   # Syllabus App
   url(r'^$', DashboardView.as_view(), name='index'),
   url(r'^', include('Syllia.apps.syllabus.urls', namespace='syllabus')),

   # Static pages
   url(r'^about/$', TemplateView.as_view(template_name='home/about.html'), name='about'),
   url(r'^contact/$', TemplateView.as_view(template_name='home/contact.html'), name='contact'),
   # url(r'^rubric/$', TemplateView.as_view(template_name='home/rubric.html'), name='rubric'),
   # url(r'^dashboard/$', TemplateView.as_view(template_name='home/dashboard.html'), name='dashboard'),

   # Accounts and authentication
   url(r'^accounts/', include('authtools.urls', namespace='authtools')),
   url(r'^accounts/', include('Syllia.apps.accounts.urls', namespace='accounts')),

   # Admin
   url(r'^admin/', include(admin.site.urls)),
)

Syllia/apps/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Faculty(models.Model):
    user = models.OneToOneField(get_user_model())
    # Prevent circular imports?
    department = models.ForeignKey('syllabus.Department')

Syllia/apps/accounts/forms.py
from django import forms
from Syllia.apps.syllabus.models import Department, College


class ProfileForm(forms.Form):
    name = forms.CharField()
    college = forms.ModelChoiceField(queryset=College.objects.all())
    department = forms.ModelChoiceField(queryset=Department.objects.all())


class RegisterForm(ProfileForm):
    email = forms.EmailField(label='Email Address')
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean_confirm_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']

        if password != confirm_password:
            raise forms.ValidationError("The passwords do not match.")

        return password

    def clean_email(self):
        email = self.cleaned_data['email']

        if not "@dlsu.edu.ph" in email and not "@delasalle.ph" in email:
            raise forms.ValidationError(
                "You need to use a valid @dlsu.edu.ph or @delasalle.ph email address to sign up for this service.")

        return email

Syllia/apps/syllabus/forms.py
from django.forms import ModelForm
from Syllia.apps.syllabus.models import Feedback


class FeedbackForm(ModelForm):

    class Meta:
        model = Feedback

Syllia/apps/accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.views.generic.base import View
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.utils import simplejson

from Syllia.apps.accounts.forms import RegisterForm, ProfileForm
from Syllia.apps.accounts.models import Faculty
from Syllia.apps.syllabus.views import get_college_list, get_department_list


class RegisterView(View):
    template_name = "accounts/register.html"
    form_class = RegisterForm

    def get(self, request, *args, **kwargs):
        jsonData = {
            "collegeList": get_college_list(),
            "departmentList": get_department_list(),
        }

        context = {
            'jsonData': simplejson.dumps(jsonData)
        }

        if request.session.get('register_form'):
            context['form'] = request.session['register_form']
            del request.session['register_form']
        else:
            context['form'] = RegisterForm()

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = get_user_model().objects.create_user(
                form.cleaned_data['email'], form.cleaned_data['password'])

            user.name = form.cleaned_data['name']
            user.save()

            faculty = Faculty()
            faculty.department = form.cleaned_data['department']
            faculty.user = user
            faculty.save()

            messages.success(request, 'Successfully created your account')
            return redirect('authtools:login')

        # Not valid, return with errors
        request.session['register_form'] = form
        return redirect('accounts:register')


@csrf_protect
@login_required
def update_profile(request):
    if request.method == "POST":
        form = ProfileForm(request.POST)

        if form.is_valid():
            current_user = get_user_model().objects.get(
                email=request.user.email)

            current_user.name = form.cleaned_data['name']
            current_user.save()

            current_user.faculty.department = form.cleaned_data['department']
            current_user.faculty.save()

            messages.success(request, 'Your profile was updated')
            return redirect('index')

        messages.error(request, 'Something went wrong')
        request.session['profile_form'] = form
        return redirect('index')

    raise Http404


@csrf_protect
@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your password has been changed')
            return redirect('index')

        messages.error(request, 'Something went wrong')
        request.session['change_password_form'] = form
        return redirect('index')

    raise Http404

Syllia/apps/syllabus/views.py
# Create your views here.

from datetime import datetime, timedelta

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.views.generic.base import View
from django.http import Http404, HttpResponse, HttpResponseServerError
from django.shortcuts import render, redirect
from django.utils import simplejson, timezone
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required

from Syllia.apps.syllabus.models import Rubric, College, Department, Syllabus
from Syllia.apps.accounts.forms import ProfileForm
from Syllia.apps.syllabus.forms import FeedbackForm


# import logging

# Log everything, and send it to stderr.
# logging.basicConfig(level=logging.DEBUG)

class DashboardView(View):
    template_name = 'syllabus/dashboard.html'

    def get(self, request, *args, **kwargs):
        # If not authenticated, show home page
        if not request.user.is_authenticated():
            return render(request, 'home/index.html', {'home_page': True})

        # Else. Dashboard
        current_user = get_user_model().objects.get(
            email=request.user.email)

        # TODO: Make more DRY
        syllabus_set = current_user.syllabus_set.all()
        syllabusList = []

        for syllabus in syllabus_set:
            syllabusList.append({
                "pk": syllabus.id,
                "url": 'syllabus',
                "itemName": syllabus.syllabus_name,
                "lastModified": format_last_modified_time(syllabus.last_modified)
            })

        rubric_set = current_user.rubric_set.all()
        rubricList = []

        for rubric in rubric_set:
            rubricList.append({
                "pk": rubric.id,
                "url": 'rubric',
                "itemName": rubric.rubric_name,
                "lastModified": format_last_modified_time(rubric.last_modified)
            })

        profileData = {
            "college": current_user.faculty.department.college.id,
            "department": current_user.faculty.department.id
        }

        jsonData = {
            "syllabusList": syllabusList,
            "rubricList": rubricList,
            "collegeList": get_college_list(),
            "departmentList": get_department_list(),
            "profileData": profileData
        }

        context = {
            'jsonData': simplejson.dumps(jsonData)
        }

        # Load profile form
        if request.session.get('profile_form'):
            context['profile_form'] = request.session['profile_form']
            del request.session['profile_form']
        else:
            context['profile_form'] = ProfileForm(initial={
                'name': current_user.get_full_name()
            })

        # Load change password form
        if request.session.get('change_password_form'):
            context['change_password_form'] = request.session[
                'change_password_form']
            del request.session['change_password_form']
        else:
            context['change_password_form'] = PasswordChangeForm(current_user)

        return render(request, self.template_name, context)


class SyllabusView(View):
    template_name = 'syllabus/syllabus.html'

    def get(self, request, *args, **kwargs):
        current_user = get_user_model().objects.get(
            email=request.user.email)

        # Create dictionary
        jsonData = {}

        # If edit mode, load syllabus data
        if(len(args)):
            try:
                syllabus = current_user.syllabus_set.get(pk=args[0])
                jsonData['syllabusData'] = syllabus.json_data

                # Load modified time data
                jsonData['timeSinceModified'] = get_time_since_modified(
                    syllabus.last_modified)

            except Exception:
                raise Http404

        rubricList = []
        rubrics = current_user.rubric_set.all()

        for rubric in rubrics:
            rubricList.append(rubric.json())

        jsonData['rubricList'] = rubricList

        jsonData['collegeList'] = get_college_list()
        jsonData['departmentList'] = get_department_list()

        # If reached here, no arguments. Return empty form
        return render(request, self.template_name, {"jsonData": simplejson.dumps(jsonData)})

    def post(self, request, *args, **kwargs):
        # Deserialize to dictionary
        json_data = simplejson.loads(request.POST['syllabus_json'])

        current_user = get_user_model().objects.get(email=request.user.email)

        # Load or create new syllabus
        try:
            syllabus = current_user.syllabus_set.get(pk=int(json_data['pk']))
        except Exception:
            syllabus = Syllabus()

        try:
            # Initialize
            syllabus.user = current_user
            syllabus.syllabus_name = json_data['syllabusName']
            syllabus.course_code = json_data['courseCode']
            syllabus.json_data = json_data

            # Load foreign keys
            # These will throw an exception if invalid
            syllabus.department = Department.objects.get(
                pk=json_data['department'])
            if('rubric' in json_data):
                syllabus.rubric = current_user.rubric_set.get(
                    pk=json_data['rubric'])

            syllabus.save()

            response_data = {
                'viewModel': syllabus.json_data,
                'timeSinceModified': get_time_since_modified(syllabus.last_modified)
            }

            if request.POST['redirect'] == "true":
                messages.success(request, 'Saved syllabus')
                response_data['redirectTo'] = reverse('index')

            return HttpResponse(simplejson.dumps(response_data), content_type="application/json")
        except Exception:
            return HttpResponseServerError(simplejson.dumps({'message': 'You must at least have basic information before saving.'}), content_type="application/json")


@csrf_protect
@login_required
def delete_syllabus(request):
    if request.method == "POST":
        item_ids = request.POST.getlist('ids_json[]')

        response_data = {}
        current_user = get_user_model().objects.get(
            email=request.user.email)

        try:
            current_user.syllabus_set.filter(id__in=item_ids).delete()
            response_data['success'] = True
            return HttpResponse(simplejson.dumps(response_data), content_type="application/json")
        except Exception:
            return HttpResponseServerError(simplejson.dumps({'message': 'Something went wrong.'}), content_type="application/json")


class RubricView(View):
    template_name = 'syllabus/rubric.html'

    def get(self, request, *args, **kwargs):
        if(len(args)):
            current_user = get_user_model().objects.get(
                email=request.user.email)

            try:
                rubric = current_user.rubric_set.get(pk=args[0])

                jsonData = {
                    'rubricData': rubric.json_data,
                    'timeSinceModified': get_time_since_modified(rubric.last_modified)
                }

                context = {'jsonData': simplejson.dumps(jsonData)}
                return render(request, self.template_name, context)
            except Exception:
                raise Http404

        # If reached here, no arguments. Return empty form
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        # Deserialize
        json_data = simplejson.loads(request.POST['rubric_json'])

        current_user = get_user_model().objects.get(email=request.user.email)

        rubric = None
        try:
            rubric = current_user.rubric_set.get(pk=int(json_data['pk']))
        except Exception:
            rubric = Rubric()

        try:
            rubric.user = current_user
            rubric.rubric_name = json_data['rubricName']
            rubric.json_data = json_data

            rubric.save()

            messages.success(request, 'Saved rubric')
            return redirect('index')
        except Exception:
            jsonData = {
                'rubricData': json_data
            }

            context = {'jsonData': simplejson.dumps(jsonData)}
            messages.error(request, 'Please check your forms')
            return render(request, self.template_name, context)


@csrf_protect
@login_required
def delete_rubric(request):
    if request.method == "POST":
        item_ids = request.POST.getlist('ids_json[]')

        response_data = {}
        current_user = get_user_model().objects.get(
            email=request.user.email)

        try:
            current_user.rubric_set.filter(id__in=item_ids).delete()
            response_data['success'] = True
            return HttpResponse(simplejson.dumps(response_data), content_type="application/json")
        except Exception:
            return HttpResponseServerError(simplejson.dumps({'message': 'Something went wrong.'}), content_type="application/json")


class FeedbackView(View):
    template_name = 'home/feedback.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        form = FeedbackForm(request.POST)

        if form.is_valid():
            form.save()
            return render(request, 'home/feedback_thanks.html')

        return render(request, 'home/feedback.html', {'form': form})


# static methods
def format_last_modified_time(last_modified):
    if timezone.localtime(last_modified).date() == timezone.localtime(datetime.utcnow().replace(tzinfo=timezone.utc)).date():
        last_modified_string = timezone.localtime(
            last_modified).strftime('%I:%M %p')
    else:
        last_modified_string = timezone.localtime(
            last_modified).strftime('%b %d')

Syllia/templates/base.html
<!DOCTYPE html>
<!--[if IE 8]>               <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>{% block title %}Base{% endblock title %} | Syllia</title>

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "stylesheets/app.css" %}">

    <script src="{% static "javascripts/vendor/custom.modernizr.js" %}"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

    {% block head %}{% endblock head %}

</head>
<body>

    <!-- temporary, only during BETA -->
    <div class="row">
        <div id="feedback">
            <a href="{% url 'syllabus:feedback' %}" target="_blank">Feedback</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="row">
            <div class="large-12 columns navigation">
                {% if not home_page %}
                <a href="{% url "index" %}">
                    <img src="{% static "images/syllia_small.jpg" %}" />
                </a>
                {% endif %}
                <ul>
                    <li><a href="{% url "about" %}">About</a></li>
                    <li><a href="{% url "contact" %}">Contact</a></li>
                    {% if user.is_authenticated %}
                    <li>
                        <a id="account-button" href="#">My Account</a>
                        <!-- TODO: Do the login panel-->
                        <div class="account-pane">
                            <p>
                                <strong>{{ user.get_full_name }}</strong>
                                {{ user.email }}
                            </p>

                            <p>
                                <!-- TODO: Add Department and College in profiles -->
                                {% comment %}
                                <strong>Computer Technology Department</strong>
                                College of Computer Studies
                                {% endcomment %}

                                <strong>{{ user.faculty.department.department_name }}</strong>
                                {{ user.faculty.department.college.college_name }}
                            </p>
                            <hr>
                            <ul>
                                <li><a href="{% url "index" %}"><i class="icon-desktop"></i>Account Dashboard</a></li>
                                <li><a href="{% url "syllabus:syllabus" %}"><i class="icon-file-text-alt"></i>&nbsp;Create a Syllabus</a></li>
                                <li><a href="{% url "syllabus:rubric" %}"><i class="icon-table"></i>&nbsp;Create a Rubric</a></li>

                            </ul>
                            <hr>
                            <ul>
                                <li id="logout"><a href="{% url "authtools:logout" %}"><i class="icon-signout"></i>Sign Out</a></li>
                            </ul>
                        </div>
                    </li>
                    {% else %}
                    <li>
                        <a id="login-button" href="#">Sign In</a>
                        <!-- TODO: Do the login panel-->
                        <div class="login-pane">
                            <form action="{% url "authtools:login" %}" method="POST">
                                {% csrf_token %}

                                <div class="row">
                                    <div class="small-12 columns">
                                        <label for="username">Email Address</label>
                                        <input type="text" name="username">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="small-12 columns">
                                        <label for="password">Password</label>
                                        <input type="password" name="password">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="small-12 columns">
                                        <input type="submit" id="login-submit" value="SIGN IN"/>
                                        <a href="{% url 'accounts:register' %}">Create a new account!</a><br/>
                                        <a href="#">Forgot Password?</a>
                                        <!--<input type="submit" value="Login" class="green-button">-->
                                    </div>
                                </div>

                            </form>
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>

        {% block content %}{% endblock content %}

        <div class="push"></div>
    </div>

    <div class="row footer">
        <div class="large-12 columns center">
            <p>&copy; Syllia 2013 - Created by DLSU NetCentric Laboratory
                for the professors of De La Salle University</p>
            </div>
        </div>
    </div>

    <script src="{% static "javascripts/vendor/jquery.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.orbit.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.joyride.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.clearing.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.tooltips.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.topbar.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.alerts.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.interchange.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.placeholder.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.forms.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.magellan.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.section.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.cookie.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.reveal.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.abide.js" %}"></script>

    <script src="{% static "javascripts/foundation/foundation.dropdown.js" %}"></script>


    <script src="{% static "javascripts/app.js" %}"></script>

    {% block scripts %}{% endblock scripts %}
</body>
</html>